export const loadContactPage = function () {
  const content = document.getElementById("content");
  content.textContent = "";
  const headline = document.createElement("h1");
  headline.textContent = "Contact Us";
  content.appendChild(headline);
  const contactsContainer = document.createElement("ul");
  const contact1 = document.createElement("li");
  const contact2 = document.createElement("li");
  const contact3 = document.createElement("li");
  const contact4 = document.createElement("li");
  contact1.textContent = "Mama Bear: 555-555-5555";
  contact2.textContent = "Papa Bear: 444-444-4444";
  contact3.textContent = "Baby Bear: 333-333-3333";
  contact4.textContent = "Grandpa Bear: 999-999-9999";
  contactsContainer.classList.add("contactsContainer");
  contactsContainer.appendChild(contact1);
  contactsContainer.appendChild(contact2);
  contactsContainer.appendChild(contact3);
  contactsContainer.appendChild(contact4);
  content.appendChild(contactsContainer);
};
